./spmm dataset/cora.mtx 
echo "========================="
./spmm dataset/pubmed.mtx 
echo "========================="
./spmm dataset/1138_bus.mtx 
echo "========================="
./spmm dataset/mip1.mtx 
echo "========================="
./spmm dataset/conf5_4-8x8-05.mtx 
echo "========================="
./spmm dataset/cant.mtx 
echo "========================="
./spmm dataset/pdb1HYS.mtx 
echo "========================="
./spmm dataset/rma10.mtx 
echo "========================="
./spmm dataset/cop20k_A.mtx 
echo "========================="
./spmm dataset/consph.mtx 
echo "========================="
./spmm dataset/shipsec1.mtx 
echo "========================="
./spmm dataset/dc2.mtx 
echo "========================="
